name: "FluidNC ULN2003 Config"
board: "ESP32"

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 8
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  
  x:
    steps_per_mm: 85
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 10
    max_travel_mm: 200
    
    motor0:
      unipolar:
        phase0_pin: gpio.12
        phase1_pin: gpio.14
        phase2_pin: gpio.27
        phase3_pin: gpio.26

  y:
    steps_per_mm: 85
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 10
    max_travel_mm: 200

    motor0:
      unipolar:
        phase0_pin: gpio.22
        phase1_pin: gpio.23
        phase2_pin: gpio.19
        phase3_pin: gpio.18

  z:
    steps_per_mm: 85
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 8
    max_travel_mm: 100

    motor0:
      unipolar:
        phase0_pin: gpio.17
        phase1_pin: gpio.16
        phase2_pin: gpio.4
        phase3_pin: gpio.0
